### ISSUE TITLE
Test 'apiMiddleware must dispatch an error request FSA on a request error' fails in Windows

### ISSUE THREAD

**Issue by ericmash** [agraboso/redux-api-middleware#29] opened 2015-12-10 18:55 UTC
The build only failed locally on my Windows machine, but not Travis-CI.

Simply clone the project and run the tests. Tests failed with following error:

>   apiMiddleware must dispatch an error request FSA on a request error
> 
> v next handler called
> v dispatched non-error FSA has correct type property
> v dispatched non-error FSA has correct payload property
> v dispatched non-error FSA has correct meta property
> v dispatched non-error FSA has correct error property
> 
> x plan != count
>     ----------------
>       operator: fail
>       expected: 10
>       actual:   5
> 
>   x test exited without ending
>     -----------------------------
>       operator: fail
>     ....................
>  total:     148
>   passing:   137
>   failing:   11
>   duration:  5.5s

Looking into 'apiMiddleware must dispatch an error request FSA on a request error' test, the test does not call the second handler, and all the checks for the error FSA are skipped. 

Machine Information:
Windows 7 Enterprise SP1
node: v4.2.1
npm: 2.14.7

**Comment by barrystaes** [comment] 2016-02-11 11:36
I just cloned the latest: https://github.com/agraboso/redux-api-middleware/tree/2cedb9215ec24f288c98e70b514d5e8f3f0a0a03

And ran
```
npm run clear
npm run install
npm run build
npm run test
```
And all tests passed, no errors.

Machine:
Windows 10
node: v5.4.0
npm: v3.5.3

**Comment by barrystaes** [comment] 2016-02-11 11:38
I'm going to close this soon.. but let it linger for upto a week in case someone wants to comment.

**Comment by agraboso** [comment] 2016-03-02 03:00
I saw this failure too when I tried running tests with Apache enabled in my machine. The problem is that the endpoint isn't mocked in the test. Left a comment about it in #45.

**Closed** 2017-11-20 20:11 UTC
Labels: bug
