### ISSUE TITLE
Undefined action "type" property when bundling with webpack

### ISSUE THREAD

**Issue by sgentry** [agraboso/redux-api-middleware#50] opened 2016-03-04 20:10 UTC
When I bundle my app using webpack, for production, with this plugin defined:

`new webpack.DefinePlugin({
        'process.env': {NODE_ENV: JSON.stringify('production')}
 })`

I get the following error:

`Actions may not have an undefined "type" property. Have you misspelled a constant?`

Everything works great when I'm running in development mode.  Anyone else run into this issue or have an idea what I may be doing wrong? Thanks for any suggestions...

**Comment by barrystaes** [comment] 2016-03-07 15:47
I'd be happy to hear why you believe this issue is caused by (or related to) redux-api-middleware, but until then i'm closing this issue.

As to resolving your issue, i suggest you look into what JS library usually throws this error, and on what file it does so.

**Closed by barrystaes** 2016-03-07 15:47 UTC
