### ISSUE TITLE
Hey Agraboso, are you still interested in maintaining this project?

### ISSUE THREAD

**Issue by peterpme** [agraboso/redux-api-middleware#96] opened 2016-08-06 00:44 UTC
Hey @agraboso - are you still interested in maintaining this project?

It looks like you're active on Github.

Thanks!

**Comment by agraboso** [comment] 2016-08-07 19:22
@peterpme Are *you* interested? I haven't done any JS in a while, haven't kept up with the breakneck pace of the ecosystem. I had help at one point, but that person disappeared...

**Comment by peterpme** [comment] 2016-08-07 23:25
Hey @agraboso,

Yes. I'm actively using this library. I've since forked it myself, but it takes a lot of effort for folks to find what they're looking for when they don't know it's there!

Let me know how you'd like to move forward 😄 

Thanks

**Comment by agraboso** [comment] 2016-08-13 23:45
@peterpme I just pushed a couple of commits to the `next` branch &mdash; nothing major, just updating dependencies, but it is movement.

I want to act on the following:

- #58: Given that browsers are slowly implementing `fetch`, I think we should remove `isomorphic-fetch` as a dependency and explicitly request users of the library to polyfill `fetch`. This would also fix #75 and make testing easier in general.
- #78: Passing the whole store instead of `getState` is trivial and has use cases.
- #80: I had never thought of this, but I wholeheartedly agree that `redux-api-middleware` should be transparent to non-RSAAs.
- #26: Network errors should probably result in failure FSAs rather than errored request FSAs. I haven't thought this through though (and I can't quite recall what the problem was that I alluded to in #25). What are your thoughts?

There are, of course, quite a few other issues and pull requests that I'd like to address, but let's take things one step at a time.

Most importantly: what have you done with `redux-api-middleware`? I see you've forked it, but I cannot see any commits on your fork.

**Comment by seb0zz** [comment] 2016-08-18 15:49
@agraboso could you provide a new npm release so that fixes like removal of `isomorphic-fetch` can be installed the standard npm way? Would be awesome!

**Comment by agraboso** [comment] 2016-08-18 21:27
@seb0zz I will do so soon. My latest commits were a bit rushed and I want to make sure things work before pushing a new version to `npm`. It would help if you could test it and let me know if everything works for you or whether something seems to be broken.

**Comment by CoteViande** [comment] 2016-08-28 20:10
Trying to make the beta version of redux-api-middleware#next rolling on my project to test it, I ran 
`(r)npm install --save "git+https://github.com/agraboso/redux-api-middleware.git#next"`

and I get the following error:

`Requiring unknown module 'redux-api-middleware'. [...]`

Although the package.json does contain `"redux-api-middleware": "git+https://github.com/agraboso/redux-api-middleware.git#next"`, and this only happens when I `npm install` the beta version
Did I make a mistake while installing a beta version? Does it require a different import?

**Comment by cevou** [comment] 2016-09-21 13:28
@agraboso Are you still planning to publish a pre version to npm?

**Comment by MrMotski** [comment] 2016-10-08 20:01
I'm having the same issue as @CoteViande , npm installed any of the commits on next causing this..

**Comment by mgriepentrog** [comment] 2016-10-11 02:07
I think this is the cause: https://github.com/npm/npm/issues/3055. I'm able to work around this by cloning redux-api-middleware, running `npm install` in the cloned directory, and then running `npm install ../redux-api-middleware -S` in my project directory. This ensures the `prepublish ` step is run. It'd be great if the 2.0.0-beta.1 package could be published in some capacity soon.

**Comment by MrOggy85** [comment] 2016-11-16 08:18
How can I get involved in the project? There are PRs that needs to be merged, new releases to be made and npm to be updated... Who has access to the project? @agraboso

**Comment by mlippens** [comment] 2017-03-14 12:53
Any updates on this? I'd like to also have these issues fixed. We need someone to maintain this project, or at least provide us with some small fixes.

**Comment by barrystaes** [comment] 2017-04-20 12:18
https://github.com/agraboso/redux-api-middleware/issues/124

**Closed** 2017-05-01 16:47 UTC
